#!/usr/bin/env bash
# gen-adapters.sh — generate provider entry-point stubs from a manifest.
#
# Rules:
#   - Adapters are GENERATED, never hand-edited. If you need to change what an
#     agent is told, edit /AGENTS.md (or a scoped <subdir>/AGENTS.md) and
#     re-run this script. Do not edit CLAUDE.md, GEMINI.md, etc. directly.
#   - An adapter containing any instruction content is a bug. If you find one,
#     regenerate it with this script and diff against what's committed.
#   - Adding a provider means adding one line to the MANIFEST array below.
#     Nothing else in this script should need to change.
#
# Usage: scripts/gen-adapters.sh   (run from repo root or anywhere; it cd's to
# the repo root itself)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# --- MANIFEST: one filename per provider entry-point. Add a line, re-run. ---
MANIFEST=(
  "CLAUDE.md"
  "GEMINI.md"
  "COPILOT.md"
  "KIMI.md"
)

read -r -d '' ADAPTER_BODY <<'BODY' || true
<!-- GENERATED by scripts/gen-adapters.sh — do not edit -->
Read and follow /AGENTS.md.
All canonical repository instructions live there.
Do not duplicate or override them here.
BODY

for filename in "${MANIFEST[@]}"; do
  printf '%s\n' "$ADAPTER_BODY" > "$filename"
  echo "generated $filename"
done
